### ISSUE TITLE
Publish on crates.io

### ISSUE THREAD

**Issue by danielnehrig** [lukechu10/mdsycx#1]
there is no crate even though the website links to one

**Comment by lukechu10** [comment]
Yes I'm planning to publish a release soon but there are a few things I wish to finish up. Also it currently relies on an unpublished version of sycamore so I will need to publish that first.

If you want to use this, you could rely on a git dependency for now.

**Comment by danielnehrig** [comment]
i've tried that but adding the crate results in a error for me
```
error[E0599]: no method named `to_web_sys` found for type parameter `G` in the current scope
   --> /Users/dNehrig/.cargo/git/checkouts/mdsycx-fc781c53a3901389/2bd0e21/mdsycx/src/components.rs:124:45
    |
92  | fn events_to_view<'a, G: Html>(
    |                       - method `to_web_sys` not found for this type parameter
...
124 |                             let node = node.to_web_sys();
    |                                             ^^^^^^^^^^ method not found in `G`
```
to be fair im using perseus for building my app

**Comment by lukechu10** [comment]
> i've tried that but adding the crate results in a error for me
> 
> ```
> error[E0599]: no method named `to_web_sys` found for type parameter `G` in the current scope
>    --> /Users/dNehrig/.cargo/git/checkouts/mdsycx-fc781c53a3901389/2bd0e21/mdsycx/src/components.rs:124:45
>     |
> 92  | fn events_to_view<'a, G: Html>(
>     |                       - method `to_web_sys` not found for this type parameter
> ...
> 124 |                             let node = node.to_web_sys();
>     |                                             ^^^^^^^^^^ method not found in `G`
> ```
> 
> to be fair im using perseus for building my app

Yes because we are relying on unpublished version of sycamore. You'll need to patch sycamore like here:
https://github.com/lukechu10/mdsycx/blob/2bd0e21e046bf6acd7e002b7bc80d04dca76c08f/Cargo.toml#L4-L5

**Comment by lukechu10** [comment]
[This crate is now published](https://crates.io/crates/mdsycx)!
