### ISSUE TITLE
Component Trait not implemented on MDSycX function?

### ISSUE THREAD

**Issue by vangourd** [lukechu10/mdsycx#5]
I'm confused. This may not be an actual bug but just an ID10T error by me. 

```
the trait bound `&for<'a> fn(sycamore_reactive::BoundedScope<'a, 'a>, MdSycXProps<'a, _>) -> sycamore_core::view::View<_> {MDSycX::<_>}: sycamore::component::Component<'_, _, _, _>` is not satisfied
the trait `sycamore::component::Component<'_, _, _, _>` is not implemented for `&for<'a> fn(sycamore_reactive::BoundedScope<'a, 'a>, MdSycXProps<'a, _>) -> sycamore_core::view::View<_> {MDSycX::<_>}
```

I'm receiving this error when handing off the `pased.body` to an MDSycX. I can see `#[component]` on the MDSycX function so I don't understand why I'm receiving this error. 

```
use sycamore::prelude::*;
use mdsycx::{parse, MDSycX};
use crate::model::posts::{get_post};

async fn fetch_post() {
    let md_string = get_post(String::from("test.md"));

}

#[component]
pub async fn PostList<G: Html>(cx: Scope<'_>) -> View<G> {


    let req = get_post(String::from("test.md"));

    let result = req.await;

    match result {
        Ok(value) => {
            let parsed = parse::<()>(&value).unwrap();

            view! { cx,
                MDSycX(cx=cx,body=parsed.body)
            }
        }
        Err(error) => {
            println!("{error:?}");
            view! { cx,
                table {
                    tbody {
                        (format!("Unable to render post. {error:?}"))
                    }
                }
            }
        }
    }
    
    
}
```

![image](https://github.com/lukechu10/mdsycx/assets/22150353/b5cfa53e-5a2f-4a1c-8615-0bc79206dd5d)

**Comment by lukechu10** [comment]
You don't need to pass in `cx=cx` since Sycamore does that automatically for you already. However, it seems like the error message is about something else? I'm a bit confused about this as well.

**Comment by vangourd** [comment]
Ah fair. I've now removed `cx=cx` and I'm still getting the same error message. I'll try and investigate further.

**Comment by vangourd** [comment]
Snippet from my Cargo.toml for documentation
```

[dependencies]
sycamore = { version="0.9.0-beta.1", features=['ssr','hydrate','suspense']}
sycamore-router = "0.9.0-beta.1"
wasm-bindgen-futures = "0.4.24"
serde = { version = "1.0.80", features = ["derive"] }
wasm-bindgen = {version="0.2.84"}
serde-wasm-bindgen = "0.5.0"
mdsycx = "0.1.0"

[dependencies.web-sys]
version = "0.3.4"
features = [
  'Headers',
  'Request',
  'RequestInit',
  'RequestMode',
  'Response',
  'Window',
]
```

**Comment by lukechu10** [comment]
> Snippet from my Cargo.toml for documentation
> 
> ```
> 
> [dependencies]
> sycamore = { version="0.9.0-beta.1", features=['ssr','hydrate','suspense']}
> sycamore-router = "0.9.0-beta.1"
> wasm-bindgen-futures = "0.4.24"
> serde = { version = "1.0.80", features = ["derive"] }
> wasm-bindgen = {version="0.2.84"}
> serde-wasm-bindgen = "0.5.0"
> mdsycx = "0.1.0"
> 
> [dependencies.web-sys]
> version = "0.3.4"
> features = [
>   'Headers',
>   'Request',
>   'RequestInit',
>   'RequestMode',
>   'Response',
>   'Window',
> ]
> ```

Ah you're using two different versions of Sycamore. `mdsycx` is still on `v0.8.x` so it won't work with `v0.9`.

**Comment by vangourd** [comment]
Ah perfect thanks!
